week_04/day_03/02_one_to_many_lab/one_to_many_solution/models/author.py
class Author:
    def __init__(self, first_name, last_name, id = None):
        self.first_name = first_name
        self.last_name = last_name
        self.id = id

    def full_name(self):
        return f"{self.first_name} {self.last_name}"

week_04/day_03/02_one_to_many_lab/one_to_many_solution/models/book.py
class Book:

    def __init__(self, title, genre, publisher, author,  id = None, ):
        self.title = title
        self.genre = genre
        self.publisher = publisher
        self.author = author
        self.id = id

    

week_04/day_03/02_one_to_many_lab/one_to_many_solution/app.py
from flask import Flask, render_template

from controllers.books_controller import books_blueprint

app = Flask(__name__)

app.register_blueprint(books_blueprint)

@app.route('/')
def home():
    return render_template('index.html')

if __name__ == '__main__':
    app.run(debug=True)

week_04/day_03/02_one_to_many_lab/one_to_many_solution/controllers/books_controller.py
from flask import Flask, render_template, request, redirect
from flask import Blueprint
from models.book import Book
import repositories.book_repository as book_repository
import repositories.author_repository as author_repository

books_blueprint = Blueprint("books", __name__)

@books_blueprint.route("/books")
def books():
    books = book_repository.select_all() # NEW
    return render_template("books/index.html", all_books = books)

# NEW
# GET '/books/new'
@books_blueprint.route("/books/new", methods=['GET'])
def new_book():
    authors = author_repository.select_all()
    return render_template("books/new.html", all_authors = authors)

# CREATE
# POST '/books'
@books_blueprint.route("/books",  methods=['POST'])
def create_book():
    title    = request.form['title']
    genre = request.form['genre']
    publisher   = request.form['publisher']
    author  = author_repository.select(request.form['author_id'])
    book = Book(title, genre, publisher, author)
    book_repository.save(book)
    return redirect('/books')


# SHOW
# GET '/books/<id>'
@books_blueprint.route("/books/<id>", methods=['GET'])
def show_book(id):
    book = book_repository.select(id)
    return render_template('books/show.html', book = book)

# EDIT
# GET '/books/<id>/edit'
@books_blueprint.route("/books/<id>/edit", methods=['GET'])
def edit_book(id):
    book = book_repository.select(id)
    authors = author_repository.select_all()
    return render_template('books/edit.html', book = book, all_authors = authors)

# UPDATE
# PUT '/books/<id>'
@books_blueprint.route("/books/<id>", methods=['POST'])
def update_book(id):
    title    = request.form['title']
    genre = request.form['genre']
    publisher   = request.form['publisher']
    author  = author_repository.select(request.form['author_id'])
    book = Book(title, genre, publisher, author, id)
    print(book.author.full_name())
    book_repository.update(book)
    return redirect('/books')

# DELETE
# DELETE '/books/<id>'
@books_blueprint.route("/books/<id>/delete", methods=['POST'])
def delete_book(id):
    book_repository.delete(id)
    return redirect('/books')

week_04/day_03/02_one_to_many_lab/one_to_many_solution/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <title>My Book List</title>
</head>
<body>
  <header>
    <nav>
      <ul class="menu">
        <li><a href="{{ url_for('home') }}">Home</a></li>
        <li><a href="{{ url_for('books.books') }}">Books</a></li>
        <li><a href="{{ url_for('books.new_book') }}">New Book</a></li>
      </ul>
    </nav>
  </header>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>

  {%block home%}
  {% endblock %}
</body>
</html>

week_04/day_03/02_one_to_many_lab/one_to_many_solution/templates/books/edit.html
{% extends "base.html" %}
{% block content %}

<form action="/books/{{book.id}}" method="post">
  <div>
    <label for="title">Title:</label>
    <input type="text" id="title" name="title" value="{{book.title}}" required>
  </div>

  <div>
    <label for="genre">Genre:</label>
    <input type="text" id="genre" name="genre" value="{{book.genre}}" required autofocus>
  </div>

  <div>
    <label for="completed">Publisher:</label>
    <input type="text" id="publisher" name="publisher" value="{{book.publisher}}" required autofocus>
  </div>

  <div>
    <label for="author">Author:</label>
    <select id="author" name="author_id">
      {% for author in all_authors %}
        <option value="{{ author.id }}"
          {% if book.author.id == author.id %} selected="selected"{% endif %}>
          {{ author.full_name() }}
        </option>
      {% endfor %}
    </select>
  </div>

  <button type="submit">Update Book</button>

</form>

{% endblock %}

week_04/day_03/02_one_to_many_lab/one_to_many_solution/templates/books/index.html
{% extends "base.html" %}
{% block content %}


{% for book in all_books %}
  <div class="book">
    <div class="content">
      <a href="/books/{{book.id}}">{{book.title}}</a>
      <div class="title">
        {{book.genre}}
        <span class="publisher">{{book.publisher}}</span>
        <p><i>{{book.author.full_name()}}</i></p>
      </div>
      <div class="buttons">

        <form class="delete-form" action="/books/{{book.id}}/delete" method="POST">
          <button class="trash-button"><i class="fa fa-trash-o fa-3x" style="color:red" aria-hidden="true"></i></button>
        </form>
      </div>
    </div>
  </div>
{% endfor %}

{% endblock %}

week_04/day_03/02_one_to_many_lab/one_to_many_solution/templates/books/new.html
{% extends "base.html" %}
{% block content %}

<form action="/books" method="post">

  <div>
    <label for="title">Title:</label>
    <input type="text" id="title" name="title" placeholder="Title" required autofocus>
  </div>

  <div>
    <label for="genre">Genre:</label>
    <input type="text" id="genre" name="genre" placeholder="Genre" required autofocus>
  </div>

  <div>
    <label for="publisher">Publisher:</label>
    <input type="text" id="publisher" name="publisher" placeholder="Publisher" required>
  </div>


  <div>
    <label for="author">Author:</label>
    <select id="author" name="author_id">
      {% for author in all_authors %}
        <option value="{{ author.id }}">{{ author.full_name() }}</option>
      {% endfor %}
    </select>
  </div>

  <button type="submit">Add Book</button>

</form>

{% endblock %}

week_04/day_03/02_one_to_many_lab/one_to_many_solution/templates/books/show.html
{% extends "base.html" %}
{% block content %}

  <div>
    <p>{{book.title}}</p>
    <hr>
    <p>{{book.genre}}</p>
    <p>{{book.author.full_name()}}</p>
    <p>{{book.publisher}}</p>
    <p><a href="/books/{{book.id}}/edit">Edit</a></p>
  </div>

{% endblock %}

week_04/day_03/02_one_to_many_lab/one_to_many_solution/templates/index.html
{% extends "base.html" %}
{% block home %}
<section id="home-image">

</section>
{% endblock %}