week_04/day_03/01_full_stack_task_list/end_point/models/task.py
class Task:

    def __init__(self, description, user, duration, completed = False,  id = None, ):
        self.description = description
        self.user = user
        self.duration = duration
        self.completed = completed
        self.id = id

    def mark_complete(self):
        self.completed = True

week_04/day_03/01_full_stack_task_list/end_point/models/user.py
class User:
    def __init__(self, first_name, last_name, id = None):
        self.first_name = first_name
        self.last_name = last_name
        self.id = id

week_04/day_03/01_full_stack_task_list/end_point/app.py
from flask import Flask, render_template

from controllers.tasks_controller import tasks_blueprint

app = Flask(__name__)

app.register_blueprint(tasks_blueprint)

@app.route('/')
def home():
    return render_template('index.html')

if __name__ == '__main__':
    app.run(debug=True)

week_04/day_03/01_full_stack_task_list/end_point/controllers/tasks_controller.py
from flask import Flask, render_template, request, redirect
from flask import Blueprint
from models.task import Task
import repositories.task_repository as task_repository
import repositories.user_repository as user_repository

tasks_blueprint = Blueprint("tasks", __name__)

@tasks_blueprint.route("/tasks")
def tasks():
    tasks = task_repository.select_all() # NEW
    return render_template("tasks/index.html", all_tasks = tasks)

# NEW
# GET '/tasks/new'
@tasks_blueprint.route("/tasks/new", methods=['GET'])
def new_task():
    users = user_repository.select_all()
    return render_template("tasks/new.html", all_users = users)

# CREATE
# POST '/tasks'
@tasks_blueprint.route("/tasks",  methods=['POST'])
def create_task():
    description = request.form['description']
    user_id     = request.form['user_id']
    duration    = request.form['duration']
    completed   = request.form['completed']
    user        = user_repository.select(user_id)
    task        = Task(description, user, duration, completed)
    task_repository.save(task)
    return redirect('/tasks')


# SHOW
# GET '/tasks/<id>'
@tasks_blueprint.route("/tasks/<id>", methods=['GET'])
def show_task(id):
    task = task_repository.select(id)
    return render_template('tasks/show.html', task = task)

# EDIT
# GET '/tasks/<id>/edit'
@tasks_blueprint.route("/tasks/<id>/edit", methods=['GET'])
def edit_task(id):
    task = task_repository.select(id)
    users = user_repository.select_all()
    return render_template('tasks/edit.html', task = task, all_users = users)

# UPDATE
# PUT '/tasks/<id>'
@tasks_blueprint.route("/tasks/<id>", methods=['POST'])
def update_task(id):
    description = request.form['description']
    user_id     = request.form['user_id']
    duration    = request.form['duration']
    completed   = request.form['completed']
    user        = user_repository.select(user_id)
    task        = Task(description, user, duration, completed, id)
    task_repository.update(task)
    return redirect('/tasks')

# DELETE
# DELETE '/tasks/<id>'
@tasks_blueprint.route("/tasks/<id>/delete", methods=['POST'])
def delete_task(id):
    task_repository.delete(id)
    return redirect('/tasks')

week_04/day_03/01_full_stack_task_list/end_point/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <title>My Task List</title>
</head>
<body>
  <header>
    <nav>
      <ul class="menu">
        <li><a href="{{ url_for('home') }}">Home</a></li>
        <li><a href="{{ url_for('tasks.tasks') }}">Tasks</a></li>
        <li><a href="{{ url_for('tasks.new_task') }}">New Task</a></li>
      </ul>
    </nav>
  </header>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

week_04/day_03/01_full_stack_task_list/end_point/templates/index.html
{% extends "base.html" %}
{% block content %}
This will be the home page. Depending on our UX we might have a dashboard here showing some stats for example.
{% endblock %}

week_04/day_03/01_full_stack_task_list/end_point/templates/tasks/edit.html
{% extends "base.html" %}
{% block content %}

<form action="/tasks/{{task.id}}" method="post">
  <div>
    <label for="description">Description:</label>
    <input type="text" id="description" name="description" value="{{task.description}}" required autofocus>
  </div>

  <div>
    <label for="duration">Duration:</label>
    <input type="number" id="duration" name="duration" value="{{task.duration}}" required>
  </div>

  <div>
    <label for="completed">Completed:</label>
    <select id="completed" name="completed">

      <option value="true"
        {% if task.completed == True %} selected="selected" {% endif %}>
        True
      </option>

      <option value="false"
        {% if task.completed == False %} selected="selected" {% endif %}>
        False
      </option>

    </select>
  </div>

  <div>
    <label for="user">User:</label>
    <select id="user" name="user_id">
      {% for user in all_users %}
        <option value="{{ user.id }}"
          {% if task.user.id== user.id %} selected="selected"{% endif %}>
          {{ user.first_name }}
        </option>
      {% endfor %}
    </select>
  </div>

  <button type="submit">Update Task</button>

</form>

{% endblock %}

week_04/day_03/01_full_stack_task_list/end_point/templates/tasks/index.html
{% extends "base.html" %}
{% block content %}


{% for task in all_tasks %}
  <div class="task">
    <div class="content">
      {{task.user.first_name}}
      <div class="description">
        <a href="/tasks/{{task.id}}">{{task.description}}</a>
        <span class="duration">{{task.duration}} mins</span>
      </div>
      <div class="buttons">

        <form class="delete-form" action="/tasks/{{task.id}}/delete" method="POST">
          <button class="trash-button"><i class="fa fa-trash-o fa-3x" style="color:red" aria-hidden="true"></i></button>
        </form>

        {% if task.completed == True %}
          <i class="fa fa-check fa-2x" style="color:green" aria-hidden="true"></i>
        {% else %}
          <i class="fa fa-times fa-2x" aria-hidden="true"></i>
        {% endif %}
      </div>
    </div>
  </div>
{% endfor %}

{% endblock %}

week_04/day_03/01_full_stack_task_list/end_point/templates/tasks/new.html
{% extends "base.html" %}
{% block content %}

<form action="/tasks" method="post">
  <div>
    <label for="description">Description:</label>
    <input type="text" id="description" name="description" placeholder="Description" required autofocus>
  </div>

  <div>
    <label for="duration">Duration:</label>
    <input type="number" id="duration" name="duration" placeholder="Duration" required>
  </div>

  <div>
    <label for="completed">Completed:</label>
    <select id="completed" name="completed">
      <option value="true">True</option>
      <option value="false">False</option>
    </select>
  </div>

  <div>
    <label for="user">User:</label>
    <select id="user" name="user_id">
      {% for user in all_users %}
        <option value="{{ user.id }}">{{ user.first_name }}</option>
      {% endfor %}
    </select>
  </div>

  <button type="submit">Add Task</button>

</form>

{% endblock %}

week_04/day_03/01_full_stack_task_list/end_point/templates/tasks/show.html
{% extends "base.html" %}
{% block content %}

  <div>
    <p>{{task.description}}</p>
    <hr>
    <p>{{task.user.first_name}}</p>
    <p>{{task.duration}} mins</p>
    <p>Completed? {{task.completed}}</p>
    <p><a href="/tasks/{{task.id}}/edit">Edit</a></p>
  </div>

{% endblock %}